data_source: local
steps: [l1, l2, l3, geo, analysis, clustering, kpi_evo]
min_year: 2015
max_year: 2018
l1_save_path: data/L1/
l2_save_path: data/L2/
analysis_path: data/analysis/
dataset: data/dataset/
common_datasets_transformations:
  - espacios_musica_copas
  - bibliotecas_museos
  - cines_teatros_auditorios
  - parques_jardines
  - hoteles
  - roba_amiga
  - instalaciones_deportivas
  - hospitales
  - lugares_culto
  - restaurantes
  - centros_comerciales
skip_processing_raw:
  - ocupacion_media_piso
  - inmigracion
  - natalidad
  - superficie